apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 335547864083.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googleclothes:fd9dc6211e22a7ccd6732ffb992d482244492dd1
        ports:
        - containerPort: 80
