apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 335547864083.dkr.ecr.us-west-2.amazonaws.com/shopping-site-earphones:b23193a3f35699a7d5abf474579c3897a335bc12
        ports:
        - containerPort: 80
