apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 335547864083.dkr.ecr.us-west-2.amazonaws.com/shopping-site-main:fd9dc6211e22a7ccd6732ffb992d482244492dd1
        ports:
        - containerPort: 80

