apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 335547864083.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlemusic:b23193a3f35699a7d5abf474579c3897a335bc12
        ports:
        - containerPort: 80
